### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'signup'

### ISSUE THREAD

**Issue by Altimis** [subzeroid/instagrapi#1997]
I get this error while using the signup method : 

self.cl = Client(request_timeout=30)
self.cl.challenge_code_handler = self.challenge_code_handler
self.cl.delay_range = [3, 7]
user = self.cl.signup(
    username, password, email, phone_number, display_name,
    year=random.randint(1970, 2004),
    month=random.randint(1, 12),
    day=random.randint(1, 28)
)

Error : 

AttributeError: 'Client' object has no attribute 'signup'

**Comment by sujay1599** [comment]
Did u import in? 



The error message you're seeing indicates that the `Client` object you're working with does not have a method called `signup`. This could be due to several reasons:

1. **Deprecated or Incorrect Library**: The `signup` method might not exist in the version of the library you're using. Some libraries, especially ones for interacting with social media platforms or APIs, remove or change methods as the platforms update their terms of service or API endpoints.

2. **Incorrect Library Usage**: You might be using the wrong class or library for the intended purpose. If you're using a library designed for interacting with a social media platform (like Instagram), it's possible that the `signup` functionality is not provided directly by the library.

3. **Outdated Documentation or Example**: The example code you’re following might be outdated, referencing a method (`signup`) that no longer exists or was never a part of the library.

### Solutions:
1. **Check the Library Documentation**: Verify the correct method to use for signing up a user, if it's even supported. Most modern libraries interacting with social platforms focus on authentication and actions performed by existing accounts rather than account creation.

2. **Use the Appropriate API or Method**: If the library doesn't support signup, you may need to look for another library or use the official API of the platform you're trying to interact with. Often, signing up new users programmatically is restricted or requires specific permissions.

3. **Library Updates**: If the `Client` object you’re using comes from a library like `instagram_private_api`, `instabot`, or something similar, check if there's a newer version or alternative method for creating accounts.

If you’re trying to automate signups for a specific platform and the library doesn’t support it, you may need to resort to web scraping (if permitted by the platform) or using an official API if available. However, be cautious with such actions as they can violate terms of service and lead to the banning of accounts or IP addresses.

**Comment by Altimis** [comment]
Hi @sujay1599  Thank you for your response. 

This is not my first time using this library. So I did all the imports and I expect the signup method to be part of the Client class. 
I checked the source code and I used the signup method the same way used in the test python file. So I don't see why the problem occurs. I'm using version 2.1.1 of Instagrapi and I also tested version 2.0.0 but I got the same error.

**Comment by Altimis** [comment]
I was able to fix this issue by getting the latest version on github (it's not updated on PyPi). 
Closing this issue.

**Comment by Altimis** [comment]
Closing after getting latest version on git (2.1.2)

**Comment by sujay1599** [comment]
Classic. I have had that happen to me aswell.

**Comment by Altimis** [comment]
@sujay1599 were you able to finish the account creation ? I created a new issue : https://github.com/subzeroid/instagrapi/issues/1999

Could you take a look at the issue I'm having please ? I'd appreciate your time.

**Comment by sujay1599** [comment]
Hmm I have not used this function yet. I may incorporate if I need. Let me see

**Comment by Altimis** [comment]
Thank you !!!
